### ISSUE TITLE
can't read files

### ISSUE THREAD

**Issue by fontiela** [ahotovec/REDPy#17]
Hi @ahotovec , I'm trying to run REDPy with local files and output warns that: 
`2018-02-12T05:00:03.300000Z`
`No data found for PGRON.PM`
`No data found for PCALD.PM`

Path in settings is pointing to the correct folder. Even when I drag and drop daily waveforms in REDpy root and leave searchdir empty, I get the same warning. Additionally,  I'm using three stations but output list two stations.  How do I know that the other station is being read?

Could it be related to mseed encoding? Any other cause? I have looked around REDpy to find a clue ... I didn't catch anything.

Any help is welcome.

**Comment by ahotovec** [comment]
First thing I would check is that the SCNL is set correctly in your configuration! I recently helped another user with a similar "can't find file" issue, and the problem was that they had put '--' in the location when the file header had the location as '' (i.e., blank). The location line was then just location=,,,,, and that did the trick!

One very messy but fast way to check is by editing redpy/trigger.py. Add print(stmp) on line 56 below where it loads the files it finds in the directory. This will print out the header of your file with the SCNL information. If your configuration file doesn't match it exactly, it will not find it. Erase the line when you're done, of course!

Let me know if you continue to have issues after checking this, and I can try to troubleshoot.

**Comment by fontiela** [comment]
RedPy is running, my problem was the  '--' in location.
@ahotovec thank you very much for your prompt answer.

**Comment by ahotovec** [comment]
Awesome! Glad it was an easy fix.
