### ISSUE TITLE
populateJunk throughs an error in the 6th time window

### ISSUE THREAD

**Issue by EvaEibl** [ahotovec/REDPy#21]
The data is read in and the scripts processes the first 5 hours of this day on 28 September without problems. However, the 6th hour is causing the following problem:

Time spent this iteration: 0.1481603701909383 minutes
2015-09-28T06:00:00.000000Z

Traceback (most recent call last):
  File "backfill.py", line 123, in <module>
    redpy.table.populateJunk(jtable, junk[i], 2, opt) # Both types of junk
  File "/data/data/code_python/REDPy/redpy/table.py", line 420, in populateJunk
    trigger['waveform'] = trig.data
  File "tables/tableextension.pyx", line 1599, in tables.tableextension.Row.__setitem__
ValueError: could not broadcast input array from shape (258062,) into shape (36872,)
Closing remaining open files:redpytable.h5...done

Does anyone know how what the problem is?

**Comment by ahotovec** [comment]
I have some thoughts. The problem is that it's trying to write data to the table, but there isn't enough space for it. The length of the array it's trying to write is 7x longer than the space allocated for it. My first guess would be that the value you've set for `nsta` in the .cfg file doesn't match how many channels you're reading in. If you changed `nsta` you'll also have to rerun initialize.py to make it change the table to allocate the correct amount of space.

Let me know if that doesn't work.

**Comment by EvaEibl** [comment]
Thanks for your prompt reply. That's a good point! You are right in that I only ran the initialize script once and not after I changed the settings. And I just realised that I need to hand over that new settings file to both functions. It is running so far without problem. Thanks for the hint.
